---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.drp
  resources:
  - drcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.drp
  resources:
  - drcronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.drp
  resources:
  - drcronjobs/status
  verbs:
  - get
  - patch
  - update
